version: 2.1


jobs:
  build:
    machine:
      image: "ubuntu-2004:202010-01"
    steps:
      - checkout
      - run:
          environment:
            REGISTRY: quay.io/giantswarm
          name: Build the CAPI docker images
          command: |
            TAG=$CIRCLE_SHA1 make -e docker-build
      - run:
          name: Login to quay
          command: |
            docker login --username $QUAY_USERNAME --password $QUAY_PASSWORD quay.io
      - run:
          name: Re-tag images
          command: |
            docker tag quay.io/giantswarm/cluster-api-controller-amd64:$CIRCLE_SHA1 quay.io/giantswarm/cluster-api-controller:$CIRCLE_SHA1
            docker tag quay.io/giantswarm/kubeadm-control-plane-controller-amd64:$CIRCLE_SHA1 quay.io/giantswarm/kubeadm-control-plane-controller:$CIRCLE_SHA1
            docker tag quay.io/giantswarm/kubeadm-bootstrap-controller-amd64:$CIRCLE_SHA1 quay.io/giantswarm/kubeadm-bootstrap-controller:$CIRCLE_SHA1
            docker tag quay.io/giantswarm/cluster-api-controller-amd64:$CIRCLE_SHA1 registry-intl.cn-shanghai.aliyuncs.com/giantswarm/cluster-api-controller:$CIRCLE_SHA1
            docker tag quay.io/giantswarm/kubeadm-control-plane-controller-amd64:$CIRCLE_SHA1 registry-intl.cn-shanghai.aliyuncs.com/giantswarm/kubeadm-control-plane-controller:$CIRCLE_SHA1
            docker tag quay.io/giantswarm/kubeadm-bootstrap-controller-amd64:$CIRCLE_SHA1 registry-intl.cn-shanghai.aliyuncs.com/giantswarm/kubeadm-bootstrap-controller:$CIRCLE_SHA1
      - run:
          name: Re-tag images for git tags
          command: |
            [[ -n $CIRCLE_TAG ]] && docker tag quay.io/giantswarm/cluster-api-controller-amd64:$CIRCLE_TAG quay.io/giantswarm/cluster-api-controller:$CIRCLE_TAG
            [[ -n $CIRCLE_TAG ]] && docker tag quay.io/giantswarm/kubeadm-control-plane-controller-amd64:$CIRCLE_TAG quay.io/giantswarm/kubeadm-control-plane-controller:$CIRCLE_TAG
            [[ -n $CIRCLE_TAG ]] && docker tag quay.io/giantswarm/kubeadm-bootstrap-controller-amd64:$CIRCLE_TAG quay.io/giantswarm/kubeadm-bootstrap-controller:$CIRCLE_TAG
            [[ -n $CIRCLE_TAG ]] && docker tag quay.io/giantswarm/cluster-api-controller-amd64:$ registry-intl.cn-shanghai.aliyuncs.com/giantswarm/cluster-api-controller:$
            [[ -n $CIRCLE_TAG ]] && docker tag quay.io/giantswarm/kubeadm-control-plane-controller-amd64:$ registry-intl.cn-shanghai.aliyuncs.com/giantswarm/kubeadm-control-plane-controller:$
            [[ -n $CIRCLE_TAG ]] && docker tag quay.io/giantswarm/kubeadm-bootstrap-controller-amd64:$ registry-intl.cn-shanghai.aliyuncs.com/giantswarm/kubeadm-bootstrap-controller:$
      - run:
          name: Push images to quay
          command: |
            docker push quay.io/giantswarm/cluster-api-controller:$CIRCLE_SHA1
            docker push quay.io/giantswarm/kubeadm-control-plane-controller:$CIRCLE_SHA1
            docker push quay.io/giantswarm/kubeadm-bootstrap-controller:$CIRCLE_SHA1
            [[ -n $CIRCLE_TAG ]] && docker push quay.io/giantswarm/cluster-api-controller:$CIRCLE_TAG
            [[ -n $CIRCLE_TAG ]] && docker push quay.io/giantswarm/kubeadm-control-plane-controller:$CIRCLE_TAG
            [[ -n $CIRCLE_TAG ]] && docker push quay.io/giantswarm/kubeadm-bootstrap-controller:$CIRCLE_TAG
      - run:
          name: Login to aliyun
          command: |
            docker login --username $ALIYUN_USERNAME --password $ALIYUN_PASSWORD registry-intl.cn-shanghai.aliyuncs.com
      - run:
          name: Push image to aliyun
          command: |
            docker push registry-intl.cn-shanghai.aliyuncs.com/giantswarm/cluster-api-controller:$CIRCLE_SHA1
            docker push registry-intl.cn-shanghai.aliyuncs.com/giantswarm/kubeadm-control-plane-controller:$CIRCLE_SHA1
            docker push registry-intl.cn-shanghai.aliyuncs.com/giantswarm/kubeadm-bootstrap-controller:$CIRCLE_SHA1
            [[ -n $CIRCLE_TAG ]] && docker push registry-intl.cn-shanghai.aliyuncs.com/giantswarm/cluster-api-controller:$CIRCLE_TAG
            [[ -n $CIRCLE_TAG ]] && docker push registry-intl.cn-shanghai.aliyuncs.com/giantswarm/kubeadm-control-plane-controller:$CIRCLE_TAG
            [[ -n $CIRCLE_TAG ]] && docker push registry-intl.cn-shanghai.aliyuncs.com/giantswarm/kubeadm-bootstrap-controller:$CIRCLE_TAG

workflows:
  version: 2
  build_and_update:
    jobs:
      - build:
          context:
            - architect
